version: '3'

services:
  app:
    build: ./src
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo
#    ports:
#      - "27017:27017"
networks:
  default:
    driver: bridge